server:
  port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.qust.entity
  mapper-locations: classpath:mapper/**/*.xml

spring:
  application:
    name: micro-demo
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/youmi
    username: root
    password: root

    dbcp2:
      min-idle: 2
      initial-size: 5
      max-total: 5
      max-wait-millis: 200


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: micro-dept-hystrix-8001
    prefer-ip-address: true


info:
  app.name: spring-cloud-study
  company.name: com.qust
  build.artifactId: $project.artifactId$
  build.version: $project.version$
